using System.Text;

namespace PrtgAPI.Tests.UnitTests.ObjectTests.TestResponses
{
    //Replace <!--(.|\n)*?--> with ""

    public class ExeFileTargetResponse : BaseTargetResponse
    {
        protected override string GetResponseText()
        {
            var builder = new StringBuilder();

            builder.Append("<!DOCTYPE html>");
            builder.Append("<html>");
            builder.Append("<head>");
            builder.Append("  <link rel=\"manifest\" href=\"/public/manifest.json.htm\">");
            builder.Append("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">");
            builder.Append("  <meta charset=\"utf-8\">");
            builder.Append("  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">");
            builder.Append("  <link id=\"prtgfavicon\" rel=\"shortcut icon\" type=\"image/png\" href=\"/icons/favicon_red.png\" />");
            builder.Append("  <title>Add Sensor (Step 2 of 2) | PRTG Continuous Integration</title>");
            builder.Append("  <link rel=\"stylesheet\" href=\"/css/prtg0.css?prtgversion=17.4.35.3441&language=en\">");
            builder.Append("  <link rel=\"stylesheet\" type=\"text/css\" href=\"/css/print.css?version=17.4.35.3441\" media=\"print\"  />");
            builder.Append("  <script src=\"/javascript/lib/jquery.js?prtgversion=17.4.35.3441&language=en\"></script>");
            builder.Append("</head>");
            builder.Append("<body id=\"mainbody\" data-theme=\"0\" class=\"systemmenu  language_en\">");
            builder.Append("<header class=\"header js-header\">");
            builder.Append("    <div class=\"menu-wrapper\">");
            builder.Append("        <button class=\"header_menu-icon js-menuIcon glyph-menu5\"></button>");
            builder.Append("        <div id=\"crumblersensorstats\" class=\"prtg-plugin header_sensorstats\" data-plugin=\"crumblerSensorStats\">");
            builder.Append("            ");
            builder.Append("<div class=\"statusinfo alert display0\" title=\"Current Alarm Count\">");
            builder.Append("    <a id=\"new_alarms\" href=\"/alarms.htm?filter_status=5&filter_status=4&filter_status=10&filter_status=13&filter_status=14\">");
            builder.Append("        <span class=\"text\">New Alarms</span>");
            builder.Append("        <span class=\"counter\">...</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo message display0\" title='Number of new logfile entries since last login'>");
            builder.Append("    <a id=\"new_message\" href=\"/log.htm\">");
            builder.Append("        <span class=\"text\">New Log Entries</span>");
            builder.Append("        <span class=\"counter\">...</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo newtickets display0\" title=\"Number of updated Tickets\">");
            builder.Append("    <a href=\"/tickets.htm?filter_user=100&filter_status=1\">");
            builder.Append("        <span class=\"text\">Updated Tickets</span>");
            builder.Append("        <span class=\"counter\">...</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"spacing\"></div>");
            builder.Append("<div class=\"statusinfo downsens display10\"");
            builder.Append("    title=\"1x Down\">");
            builder.Append("    <a href=\"/sensors.htm?id=0&filter_status=5\">");
            builder.Append("        <span class=\"icon sensr\"></span>");
            builder.Append("        <span class=\"counter\">1</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo partialdownsens display0\"");
            builder.Append("    title=\"x Down (Partial)\">");
            builder.Append("    <a href=\"/sensors.htm?id=0&filter_status=14\">");
            builder.Append("        <span class=\"icon sensq\"></span>");
            builder.Append("        <span class=\"counter\"></span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo downacksens display10\"");
            builder.Append("    title=\"1x Down (Acknowledged)\">");
            builder.Append("    <a href=\"/sensors.htm?id=0&filter_status=13\">");
            builder.Append("        <span class=\"icon senso\"></span>");
            builder.Append("        <span class=\"counter\">1</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo warnsens display10\"");
            builder.Append("    title=\"1x Warning\">");
            builder.Append("    <a href=\"/sensors.htm?id=0&filter_status=4\">");
            builder.Append("        <span class=\"icon sensy\"></span>");
            builder.Append("        <span class=\"counter\">1</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo upsens display220\"");
            builder.Append("    title=\"22x Up\">");
            builder.Append("    <a href=\"/sensors.htm?id=0&filter_status=2&filter_status=3\">");
            builder.Append("        <span class=\"icon sensg\"></span>");
            builder.Append("        <span class=\"counter\">22</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo pausedsens display30\"");
            builder.Append("    title=\"3x Paused\">");
            builder.Append("    <a href=\"/sensors.htm?id=0&filter_status=7&filter_status=8&filter_status=9&filter_status=11&filter_status=12\">");
            builder.Append("        <span class=\"icon sensb\"></span>");
            builder.Append("        <span class=\"counter\">3</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo unusualsens display0\"");
            builder.Append("    title=\"x Unusual\">");
            builder.Append("    <a href=\"/sensors.htm?id=0&filter_status=10\">");
            builder.Append("        <span class=\"icon sensp\"></span>");
            builder.Append("        <span class=\"counter\"></span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("<div class=\"statusinfo undefinedsens display10\"");
            builder.Append("    title=\"1x Unknown\">");
            builder.Append("    <a href=\"/sensors.htm?id=0&filter_status=0&filter_status=6&filter_status=1\">");
            builder.Append("        <span class=\"icon sensx\"></span>");
            builder.Append("        <span class=\"counter\">1</span>");
            builder.Append("    </a>");
            builder.Append("</div>");
            builder.Append("        </div>");
            builder.Append("        <div id=\"quickbar\" class=\"header_quickbar\">");
            builder.Append("            <form class=\"header_searchForm\" onsubmit=\"_Prtg.Hjax.loadLink('/search.htm?searchtext='+encodeURIComponent($(this).find('#searchtext').val())); return false;\" method=\"get\"");
            builder.Append("                id=\"searchform\">");
            builder.Append("                <input tabindex=\"1\" id=\"searchtext\" class=\"searchstring\" data-trigger=\"manual\" type=\"text\" placeholder=\"Search...\" name=\"searchtext\">");
            builder.Append("                <label class=\"glyph-search2\" for=\"searchtext\"></label>");
            builder.Append("            </form>");
            builder.Append("            <div class=\"header-logout\">");
            builder.Append("                <a class=\"glyph-off logout\" href=\"/index.htm?logout=1\" title=\"Logout\"></a>");
            builder.Append("                <div class=\" inactivitylogout hide\" data-plugin=\"activity\"");
            builder.Append("                    data-loggedout-text=\" You were automatically logged out after a certain time of inactivity.\"");
            builder.Append("                    title=\"After a certain time of inactivity, you will be automatically logged out.\"></div>");
            builder.Append("            </div>");
            builder.Append("        </div>");
            builder.Append("        <nav id=\"header_menu\" class=\"header_menu\">");
            builder.Append("            ");
            builder.Append("<ul id=\"main_menu\" class=\"menu\">");
            builder.Append("  <li>");
            builder.Append("    <a class=\"homeicon\" href=\"/home\">Home</a>");
            builder.Append("    <ul>");
            builder.Append("      ");
            builder.Append("      <li style=\"display:none;\">");
            builder.Append("        Switch Cluster Node<span class=\"ui-icon ui-icon-carat-1-e\"></span>");
            builder.Append("          ");
            builder.Append("      </li>");
            builder.Append("      <li class=\"menudivider\">");
            builder.Append("        <a href=\"/welcome.htm\">Welcome to PRTG</a>");
            builder.Append("      </li>");
            builder.Append("      <li onclick=\"_Prtg.Contextmenu.makeThisMyHomepage();return false;\" style=\"\">");
            builder.Append("        Make This My Homepage");
            builder.Append("      </li>");
            builder.Append("    </ul>");
            builder.Append("  </li>");
            builder.Append("  <li id=\"devicesmenuitem\"><a href=\"group.htm?id=0&tabid=1\">Devices</a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"group.htm?id=0&tabid=1\" class=\"hideforreadonlyuser\" >All</a></li>");
            builder.Append("<li><a href=\"devices.htm?filter_favorite=1\">Favorite Devices</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"devices.htm\">Device List</a></li>");
            builder.Append("<li><a href=\"dependencies.htm?id=0\">Dependencies</a></li>");
            builder.Append("<li><a href=\"#\"  class=\"nohjax hideforreadonlyuser\"  onclick=\"_Prtg.objectTools.addObject0('group', {preselect:1});return false;\">Add Group</a></li>");
            builder.Append("<li><a href=\"#\"  class=\"nohjax hideforreadonlyuser\"  onclick=\"_Prtg.objectTools.addObject0('autodiscovery', {preselect:1});return false;\">Add Auto-Discovery Group</a></li>");
            builder.Append("<li><a href=\"#\"  class=\"nohjax hideforreadonlyuser\"  onclick=\"_Prtg.objectTools.addObject0('device', {preselect:1});return false;\">Add Device</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href=\"libraries.htm\">Libraries</a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"libraries.htm\">All</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"#\"  class=\"nohjax hideforreadonlyuser\"  onclick=\"_Prtg.objectTools.addObject.apply(this, ['new', 'library',{'target':'root','redirect':'/library.htm?tabid=2'}]);return false;\">Add Library</a></li>");
            builder.Append("<li>Select Library <span class=\"ui-icon ui-icon-carat-1-e\"></span>");
            builder.Append("<ul><li><a id=\"715\" href=\"library.htm?id=715\">All bandwidth sensors</a></li>");
            builder.Append("<li><a id=\"718\" href=\"library.htm?id=718\">All CPU load sensors</a></li>");
            builder.Append("<li><a id=\"716\" href=\"library.htm?id=716\">All diskspace sensors</a></li>");
            builder.Append("<li><a id=\"717\" href=\"library.htm?id=717\">All memory sensors</a></li>");
            builder.Append("<li><a id=\"710\" href=\"library.htm?id=710\">All sensors grouped by state</a></li>");
            builder.Append("<li><a id=\"712\" href=\"library.htm?id=712\">All VMware sensors</a></li>");
            builder.Append("<li><a id=\"719\" href=\"library.htm?id=719\">Sensors grouped by priority</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li id=\"sensorsmenuitem\"><a href=\"sensors.htm\">Sensors</a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"sensors.htm\">All</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"addsensor0.htm\" class=\"hideforreadonlyuser\" >Add Sensor</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"sensors.htm?filter_favorite=1\">Favorite Sensors</a></li>");
            builder.Append("<li><a href=\"top10.htm\">Top 10 Lists  <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"top10.htm\">All Sensors</a></li>");
            builder.Append("<li><a href=\"top10.htm?id=1\">Local Probe<span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"top10.htm?id=2070\">Servers<span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"top10.htm?id=2073\">Group<span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"top10.htm?id=2082\">NestedGroup</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">By Current Value  <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href='#' onclick=\"false\">Fastest  <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?sortby=lastvalue&filter_type=ping&display=101&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Ping</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=lastvalue&filter_type=port&display=102&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Port</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=lastvalue&filter_tags=@tag(httpsensor)&display=103&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Webpages</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=lastvalue&filter_type=pop3&filter_type=imap&filter_type=smtp&display=104&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">IMAP/POP3/SMTP</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=lastvalue&filter_type=ftp&display=105&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">FTP</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">Slowest  <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?sortby=-lastvalue&filter_type=ping&display=201&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Ping</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=-lastvalue&filter_type=port&display=202&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Port</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=-lastvalue&filter_tags=@tag(httpsensor)&display=203&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Webpages</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=-lastvalue&filter_type=pop3&filter_type=imap&filter_type=smtp&display=204&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">IMAP/POP3/SMTP</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=-lastvalue&filter_type=ftp&display=205&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">FTP</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">Most Used  <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?sortby=-lastvalue&filter_tags=@tag(bandwidthsensor)&display=306&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Bandwidth Sensors</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=-lastvalue&filter_tags=@tag(cpuloadsensor)&display=307&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">CPUs</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=lastvalue&filter_tags=@tag(diskspacesensor)&display=308&filter_lastvalue=@below(10100)&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Disks</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=lastvalue&filter_tags=@tag(memorysensor)&display=309&filter_lastvalue=@below(10100)&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Memory</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">Least Used <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?sortby=lastvalue&filter_tags=@tag(bandwidthsensor)&display=406&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Bandwidth Sensors</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=lastvalue&filter_tags=@tag(cpuloadsensor)&display=407&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">CPUs</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=-lastvalue&filter_tags=@tag(diskspacesensor)&display=408&filter_lastvalue=@below(10100)&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Disks</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=-lastvalue&filter_tags=@tag(memorysensor)&display=409&filter_lastvalue=@below(10100)&filter_status=3&filter_status=13&filter_status=14&filter_status=4&filter_status=10\">Memory</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">By Current Status <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_status=3\">Up</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"sensors.htm?filter_status=4\">Warning</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_status=5\">Down</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"sensors.htm?filter_status=13\">Down (Acknowledged)</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_status=10\">Unusual</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_status=7&filter_status=9&filter_status=8&filter_status=12&filter_status=11\">Paused</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_status=1&filter_status=2&filter_status=0\">Unknown</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li class=\"menudivider\"><a href='#' onclick=\"false\">By Uptime/Downtime <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?sortby=uptime&columns=group,device,sensor,status,message,lastvalue,uptime,uptimetime,downtime,downtimetime\">Best Uptime (%)</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=uptimetime&columns=group,device,sensor,status,message,lastvalue,uptime,uptimetime,downtime,downtimetime\">Highest Uptime (Time)</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=downtime&columns=group,device,sensor,status,message,lastvalue,uptime,uptimetime,downtime,downtimetime\">Worst Downtime (%)</a></li>");
            builder.Append("<li><a href=\"sensors.htm?sortby=downtimetime&columns=group,device,sensor,status,message,lastvalue,uptime,uptimetime,downtime,downtimetime\">Highest Downtime (Time)</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">By Type <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href='#' onclick=\"false\">C&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_type=corestate\">Core Health</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">E&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_type=exe\">EXE/Script</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">H&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_type=http\">HTTP</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">N&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_type=netflow9header\">NetFlow V9</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">P&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_type=ping\">Ping</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=probestate\">Probe Health</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">R&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_type=remotedesktop\">RDP (Remote Desktop)</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">S&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_type=aggregation\">Sensor Factory</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=snmpcustom\">SNMP Custom</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=ssl\">SSL Security Check</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=systemstate\">System Health</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">W&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_type=wmiprocessor\">Windows CPU Load</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wminetwork\">Windows Network Card</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wmipagefile\">Windows Pagefile</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wmiphysicaldiskv2\">Windows Physical Disk I/O BETA</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wmiuptime\">Windows System Uptime</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wmidiskspace\">WMI Free Disk Space (Multi Disk)</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wmilogicaldiskv2\">WMI Logical Disk I/O BETA</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wmimemory\">WMI Memory</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wmiremoteping\">WMI Remote Ping</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_type=wmiservice\">WMI Service</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li class=\"menudivider\"><a href='#' onclick=\"false\">By Tag <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href='#' onclick=\"false\">B&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(bandwidthsensor)\">bandwidthsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">C&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(C_OS_VMware)\">C_OS_VMware</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(corehealthsensor)\">corehealthsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(cpuloadsensor)\">cpuloadsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">D&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(diskspacesensor)\">diskspacesensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">E&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(exesensor)\">exesensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">F&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(factorysensor)\">factorysensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">H&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(httpsensor)\">httpsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">M&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(memorysensor)\">memorysensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">N&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(netflowsensor)\">netflowsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">P&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(pagefilesensor)\">pagefilesensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(pingsensor)\">pingsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(probehealthsensor)\">probehealthsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">R&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(rdpsensor)\">rdpsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(remotepingsensor)\">remotepingsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">S&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(servicesensor)\">servicesensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(snmpcustomsensor)\">snmpcustomsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(sslsensor)\">sslsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(systemhealthsensor)\">systemhealthsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">T&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(TestGroup)\">TestGroup</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(TestProbe)\">TestProbe</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">W&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensors.htm?filter_tags=@tag(wmibandwidthsensor)\">wmibandwidthsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmicpuloadsensor)\">wmicpuloadsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmidiskspacesensor)\">wmidiskspacesensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmilogicalsensor)\">wmilogicalsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmimemorysensor)\">wmimemorysensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmipagefilesensor)\">wmipagefilesensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmiphysicaldisksensor)\">wmiphysicaldisksensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmipingsensor)\">wmipingsensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmisensor)\">wmisensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmiservicesensor)\">wmiservicesensor</a></li>");
            builder.Append("<li><a href=\"sensors.htm?filter_tags=@tag(wmiuptimesensor)\">wmiuptimesensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li class=\"menudivider\"><a href=\"sensorxref.htm\">Cross Reference <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"sensorxref.htm\">All Sensors</a></li>");
            builder.Append("<li>By Type <span class=\"ui-icon ui-icon-carat-1-e\"></span>");
            builder.Append("<ul><li><a href='#' onclick=\"false\">C&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_type=corestate\">Core Health</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">E&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_type=exe\">EXE/Script</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">H&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_type=http\">HTTP</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">N&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_type=netflow9header\">NetFlow V9</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">P&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_type=ping\">Ping</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=probestate\">Probe Health</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">R&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_type=remotedesktop\">RDP (Remote Desktop)</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">S&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_type=aggregation\">Sensor Factory</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=snmpcustom\">SNMP Custom</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=ssl\">SSL Security Check</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=systemstate\">System Health</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">W&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_type=wmiprocessor\">Windows CPU Load</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wminetwork\">Windows Network Card</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wmipagefile\">Windows Pagefile</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wmiphysicaldiskv2\">Windows Physical Disk I/O BETA</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wmiuptime\">Windows System Uptime</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wmidiskspace\">WMI Free Disk Space (Multi Disk)</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wmilogicaldiskv2\">WMI Logical Disk I/O BETA</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wmimemory\">WMI Memory</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wmiremoteping\">WMI Remote Ping</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_type=wmiservice\">WMI Service</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li>By Tag <span class=\"ui-icon ui-icon-carat-1-e\"></span>");
            builder.Append("<ul><li><a href='#' onclick=\"false\">B&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(bandwidthsensor)\">bandwidthsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">C&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(C_OS_VMware)\">C_OS_VMware</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(corehealthsensor)\">corehealthsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(cpuloadsensor)\">cpuloadsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">D&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(diskspacesensor)\">diskspacesensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">E&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(exesensor)\">exesensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">F&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(factorysensor)\">factorysensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">H&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(httpsensor)\">httpsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">M&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(memorysensor)\">memorysensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">N&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(netflowsensor)\">netflowsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">P&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(pagefilesensor)\">pagefilesensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(pingsensor)\">pingsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(probehealthsensor)\">probehealthsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">R&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(rdpsensor)\">rdpsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(remotepingsensor)\">remotepingsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">S&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(servicesensor)\">servicesensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(snmpcustomsensor)\">snmpcustomsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(sslsensor)\">sslsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(systemhealthsensor)\">systemhealthsensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">T&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(TestGroup)\">TestGroup</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(TestProbe)\">TestProbe</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href='#' onclick=\"false\">W&hellip; <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"sensorxref.htm?filter_tags=@tag(wmibandwidthsensor)\">wmibandwidthsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmicpuloadsensor)\">wmicpuloadsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmidiskspacesensor)\">wmidiskspacesensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmilogicalsensor)\">wmilogicalsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmimemorysensor)\">wmimemorysensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmipagefilesensor)\">wmipagefilesensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmiphysicaldisksensor)\">wmiphysicaldisksensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmipingsensor)\">wmipingsensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmisensor)\">wmisensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmiservicesensor)\">wmiservicesensor</a></li>");
            builder.Append("<li><a href=\"sensorxref.htm?filter_tags=@tag(wmiuptimesensor)\">wmiuptimesensor</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href=\"historicdata.htm\">View Historic Data</a></li>");
            builder.Append("<li><a href=\"similarsensors.htm\">Similar Sensors Overview</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li id=\"alarmsmenuitem\"><a href=\"alarms.htm?filter_status=5&filter_status=4&filter_status=10&filter_status=13&filter_status=14\">Alarms</a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"alarms.htm?filter_status=5&filter_status=4&filter_status=10&filter_status=13&filter_status=14\">All</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"alarmsgauges.htm\">Show as Gauges</a></li>");
            builder.Append("<li><a href=\"alarms.htm?filter_status=5&filter_status=13&filter_status=14\">Errors Only</a></li>");
            builder.Append("<li><a href=\"alarms.htm?filter_status=4\">Warnings Only</a></li>");
            builder.Append("<li><a href=\"alarms.htm?filter_status=10\">Unusuals Only</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href=\"maps.htm\">Maps</a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"maps.htm\">All</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"addmap.htm\" class=\"hideforreadonlyuser\" >Add Map</a></li>");
            builder.Append("<li>Select Map <span class=\"ui-icon ui-icon-carat-1-e\"></span>");
            builder.Append("<ul><li><a id=\"2001\" href=\"map.htm?id=2001\">Magic Map </a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href=\"reports.htm\">Reports</a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"reports.htm\">All</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"addreport.htm?id=new\" class=\"hideforreadonlyuser\" >Add Report</a></li>");
            builder.Append("<li class=\"menudivider\">Select Report <span class=\"ui-icon ui-icon-carat-1-e\"></span>");
            builder.Append("<ul><li><a id=\"400\" href=\"report.htm?id=400\">Summary report for all sensors </a></li>");
            builder.Append("<li><a id=\"415\" href=\"report.htm?id=415\">Top 100 Busy/Idle Processor Sensors </a></li>");
            builder.Append("<li><a id=\"417\" href=\"report.htm?id=417\">Top 100 Fastest/Slowest HTTP Sensors </a></li>");
            builder.Append("<li><a id=\"413\" href=\"report.htm?id=413\">Top 100 Fastest/Slowest PING Sensors </a></li>");
            builder.Append("<li><a id=\"416\" href=\"report.htm?id=416\">Top 100 Free/Full Disk Space Sensors </a></li>");
            builder.Append("<li><a id=\"414\" href=\"report.htm?id=414\">Top 100 Most/Least Used Bandwidth Sensors </a></li>");
            builder.Append("<li><a id=\"418\" href=\"report.htm?id=418\">Top 100 Most/Least Used Memory Sensors </a></li>");
            builder.Append("<li><a id=\"412\" href=\"report.htm?id=412\">Top 100 Uptime/Downtime Report </a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li class=\"menudivider\">Configuration Reports <span class=\"ui-icon ui-icon-carat-1-e\"></span>");
            builder.Append("<ul><li><a href=\"config_report_maps.htm\" class=\"nohjax\"  target=\"_blank\" >Maps</a></li>");
            builder.Append("<li><a href=\"config_report_reports.htm\" class=\"nohjax\"  target=\"_blank\" >Reports</a></li>");
            builder.Append("<li><a href=\"config_report_users.htm\" class=\"nohjax\"  target=\"_blank\" >Users & User Groups</a></li>");
            builder.Append("<li><a href=\"config_report_systemconfig.htm\" class=\"nohjax\"  target=\"_blank\" >System Configuration</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li id=\"logmenuitem\"><a href=\"log.htm\">Logs</a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"log.htm\">All</a></li>");
            builder.Append("<li class=\"menudivider\"><a href='#' onclick=\"false\"  class=\"nohjax\"  onclick=\"return false;\">Status Changes <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"log.htm?filter_status=608&filter_status=607&filter_status=620\">Up &amp; Down</a></li>");
            builder.Append("<li><a href=\"log.htm?filter_status=620&filter_status=608\">Down</a></li>");
            builder.Append("<li><a href=\"log.htm?filter_status=609\">Warning</a></li>");
            builder.Append("<li><a href=\"log.htm?filter_status=610\">Unusual</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"log.htm?filter_status=607\">Up</a></li>");
            builder.Append("<li><a href=\"log.htm?filter_status=602&filter_status=603&filter_status=604&filter_status=605&filter_status=606\">Paused/Resumed</a></li>");
            builder.Append("<li><a href=\"log.htm?filter_status=619\">Acknowledged Alarms</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li class=\"menudivider\"><a href='#' onclick=\"false\"  class=\"nohjax\"  onclick=\"return false;\">System Events <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"log.htm?filter_status=14&filter_status=612&filter_status=613&filter_status=614&filter_status=4&filter_status=5&filter_status=12&filter_status=10&filter_status=701\">Probe Related</a></li>");
            builder.Append("<li><a href=\"log.htm?filter_status=801&filter_status=802&filter_status=803&filter_status=804&filter_status=805\">Auto-Discovery</a></li>");
            builder.Append("<li><a href=\"log.htm?filter_status=13\">Notifications</a></li>");
            builder.Append("<li><a href=\"log.htm?filter_status=1&filter_status=2&filter_status=3&filter_status=6&filter_status=7&filter_status=8&filter_status=9&filter_status=10&filter_status=11\">Status Messages</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href=\"/objecthistory.htm\">Object History</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li id=\"todomenuitem\"><a href=\"tickets.htm?filter_user=100&filter_status=1\">Tickets</a>");
            builder.Append("<ul><li class=\"menudivider\"><a href=\"tickets.htm?filter_user=100&filter_status=1.htm\">All</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_user=100&filter_status=1\">My Tickets <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"tickets.htm?filter_user=100&filter_status=1\">Open</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_user=100&filter_status=2\">Resolved</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_user=100&filter_status=3\">Closed</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_user=100\">All</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href=\"tickets.htm?filter_status=1\">All Tickets <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"tickets.htm?filter_status=1\">Open</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_status=2\">Resolved</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_status=3\">Closed</a></li>");
            builder.Append("<li><a href=\"tickets.htm\">All</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li class=\"menudivider\"><a href=\"tickets.htm?filter_type=1&filter_status=1\">ToDo Tickets <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"tickets.htm?filter_type=1&filter_status=1\">Open <span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("<ul><li><a href=\"tickets.htm?filter_type=1&filter_status=1\">All</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_code=708&filter_status=1&filter_type=1\">Report Related</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_code=805&filter_status=1&filter_type=1\">Auto-Discovery Related</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_code=701&filter_code=710&filter_status=1&filter_type=1\">Probe Related</a></li>");
            builder.Append("<li class=\"menudivider\"><a href=\"tickets.htm?filter_code=704&filter_code=705&filter_code=707&filter_code=709&filter_code=711&filter_status=1&filter_type=1\">System Errors</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_code=706&filter_status=1&filter_type=1\">New Software Version</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href=\"tickets.htm?filter_type=1&filter_status=2\">Resolved</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_type=1&filter_status=3\">Closed</a></li>");
            builder.Append("<li><a href=\"tickets.htm?filter_type=1\">All</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("<li><a href=\"#\"  class=\"nohjax hideforreadonlyuser\"  onclick=\"_Prtg.objectTools.ticketAdd0({preselect:0});return false;\">Open Ticket</a></li>");
            builder.Append("</ul>");
            builder.Append("</li>");
            builder.Append("  <li style=''>");
            builder.Append("    <a href=\"/setup.htm\">Setup</a>");
            builder.Append("    <ul>");
            builder.Append("      <li class='menudivider'>");
            builder.Append("        <a href='/setup.htm'>Overview</a>");
            builder.Append("      </li>");
            builder.Append("      <li style=''>");
            builder.Append("        <a href=\"/myaccount.htm\">Account Settings<span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("        <ul>");
            builder.Append("          <li class='menudivider'>");
            builder.Append("            <a href=\"/myaccount.htm\">My Account</a>");
            builder.Append("          </li>");
            builder.Append("          <li style=''>");
            builder.Append("            <a href='/myaccount.htm?tabid=2'>Notifications</a>");
            builder.Append("          </li>");
            builder.Append("          <li style=''>");
            builder.Append("            <a href='/myaccount.htm?tabid=4'>Notification Contacts</a>");
            builder.Append("          </li>");
            builder.Append("          <li style=''>");
            builder.Append("            <a href='/myaccount.htm?tabid=3'>Schedules</a>");
            builder.Append("          </li>");
            builder.Append("        </ul>");
            builder.Append("      </li>");
            builder.Append("      <li style=''>");
            builder.Append("        <a href='/systemsetup.htm'>System Administration<span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("        <ul>");
            builder.Append("          <li class='menudivider' style=\"display:none;\">");
            builder.Append("            <a href='https://www.my-prtg.com' target=\"=_blank\">Manage Subscription</a>");
            builder.Append("          </li>");
            builder.Append("          <li class='menudivider'>");
            builder.Append("            <a href='/systemsetup.htm'>User Interface</a>");
            builder.Append("          </li>");
            builder.Append("          <li>");
            builder.Append("            <a href='/systemsetup.htm?tabid=2'>Monitoring</a>");
            builder.Append("          </li>");
            builder.Append("          <li style=''>");
            builder.Append("            <a href='/systemsetup.htm?tabid=3'>Notification Delivery</a>");
            builder.Append("          </li>");
            builder.Append("          <li>");
            builder.Append("            <a href='/systemsetup.htm?tabid=4'>Core & Probes</a>");
            builder.Append("          </li>");
            builder.Append("          <li>");
            builder.Append("            <a href='/systemsetup.htm?tabid=5'>User Accounts</a>");
            builder.Append("          </li>");
            builder.Append("          <li>");
            builder.Append("            <a href='/systemsetup.htm?tabid=6' class='menudivider'>User Groups</a>");
            builder.Append("          </li>");
            builder.Append("          <li>");
            builder.Append("            <a href='/systemsetup.htm?tabid=7'>Administrative Tools</a>");
            builder.Append("          </li>");
            builder.Append("          <li style='display:none;'>");
            builder.Append("            <a href='/systemsetup.htm?tabid=8'>Cluster</a>");
            builder.Append("          </li>");
            builder.Append("        </ul>");
            builder.Append("      </li>");
            builder.Append("      <li style=' '>");
            builder.Append("        <a href='/status.htm'>PRTG Status</a>");
            builder.Append("        <li style=' display:none;'>");
            builder.Append("          <a href='/status.htm'>PRTG Status<span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("          <ul>");
            builder.Append("            <li>");
            builder.Append("              <a href='/status.htm'>System Status</a>");
            builder.Append("            </li>");
            builder.Append("            <li style='display:none;'>");
            builder.Append("              <a href='/status.htm?tabid=2'>Cluster Status</a>");
            builder.Append("            </li>");
            builder.Append("          </ul>");
            builder.Append("        </li>");
            builder.Append("        <li style=' '>");
            builder.Append("          <a class=\"nohjax\" href='/licensing.htm?tabid=1'>License</span></a>");
            builder.Append("        </li>");
            builder.Append("        <li style=' '>");
            builder.Append("          <a href='/autoupdate.htm'>Auto-Update<span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("          <ul>");
            builder.Append("            <li>");
            builder.Append("              <a class=\"nohjax\" href='/autoupdate.htm?tabid=1'>Status</a>");
            builder.Append("            </li>");
            builder.Append("            <li>");
            builder.Append("              <a class=\"nohjax\" href='/autoupdate.htm?tabid=3'>Settings</a>");
            builder.Append("            </li>");
            builder.Append("          </ul>");
            builder.Append("        </li>");
            builder.Append("        <li style='' class='menudivider'>");
            builder.Append("          <a href='/downloads.htm'>Downloads<span class=\"ui-icon ui-icon-carat-1-e\"></span></a>");
            builder.Append("          <ul>");
            builder.Append("            <li>");
            builder.Append("              <a href='/downloads.htm?tabid=1'>Client Apps for Mobile Devices</a>");
            builder.Append("            </li>");
            builder.Append("            <li  class=\"\">");
            builder.Append("              <a href='/downloads.htm?tabid=2'>Client App for Windows (Enterprise Console)</a>");
            builder.Append("            </li>");
            builder.Append("            <li>");
            builder.Append("              <a href='/downloads.htm?tabid=3'>Remote Probe Installer</a>");
            builder.Append("            </li>");
            builder.Append("            <li>");
            builder.Append("              <a href='/downloads.htm?tabid=4'>PRTG Tools</a>");
            builder.Append("            </li>");
            builder.Append("            <li class=\"onlynotificationbrowser\">");
            builder.Append("              <a href='/downloads.htm?tabid=5'>Desktop Notifications</a>");
            builder.Append("            </li>");
            builder.Append("          </ul>");
            builder.Append("        </li>");
            builder.Append("        <li style=''>");
            builder.Append("          <a href='/api.htm'>PRTG API</a>");
            builder.Append("        </li>");
            builder.Append("        <li style=' display:none;'>");
            builder.Append("          <a class=\"nohjax\" href='/licensing.htm?tabid=3'>Enter License Key</a>");
            builder.Append("        </li>");
            builder.Append("        <li style=' '>");
            builder.Append("          <a onclick=\"_Prtg.objectTools.sendFeedback('/sendfeedback.htm?errorurl='+window.location.pathname,'');return false;\">Contact Support</a>");
            builder.Append("        </li>");
            builder.Append("      </li>");
            builder.Append("    </ul>");
            builder.Append("  </li>");
            builder.Append("</ul>");
            builder.Append("        </nav>");
            builder.Append("    </div>");
            builder.Append("</header>");
            builder.Append("<div id=\"header_breadcrumbs\" class=\"headerBreadcrumbs js-adjustToMenu\">");
            builder.Append("    <div class=\"breadcrumbs prtg-plugin\" data-plugin=\"prtg-breadcrumbs\" data-parent=\"true\"><ul class=\"crumbler\"><li><a href =\"/home\"><i class=\"breadcrumbshome glyph-home4\" title=\"Home\"></i></a></li><li class=\"\" data-breadid=\"0\"><span class=\"breadcrumbdivider\"></span><a href=\"/group.htm?id=0\">Devices</a></li><li><span class=\"breadcrumbdivider\"></span><span>Add Sensor (Step 2 of 2)</span></li></ul></div><span class=\"breadcrumbdivider\"></span>");
            builder.Append("</div>");
            builder.Append("<div id=\"container\" class=\"js-adjustToMenu\">");
            builder.Append("<div class=\"breadcrumbs prtg-plugin hide\" data-plugin=\"prtg-breadcrumbs\" data-child=\"true\"><ul class=\"crumbler\"><li><a href =\"/home\"><i class=\"breadcrumbshome glyph-home4\" title=\"Home\"></i></a></li><li class=\"\" data-breadid=\"0\"><span class=\"breadcrumbdivider\"></span><a href=\"/group.htm?id=0\">Devices</a></li><li class=\"breadcrumbmenu\" data-breadid=\"1\"><span class=\"breadcrumbdivider\"></span><a class=\"probenodemenu nopopup\" data-id=\"1\" href=\"/probenode.htm?id=1\">Local Probe</a><li class=\"breadcrumbmenu\" data-breadid=\"2070\"><span class=\"breadcrumbdivider\"></span><a class=\"groupmenu nopopup\" data-id=\"2070\" href=\"/group.htm?id=2070\">Servers</a></li></li><li><span class=\"breadcrumbdivider\"></span><a href=\"/device.htm?id=2055\" class=\"devicemenu nopopup breadcrumbmenu \" data-id=\"2055\">ci-prtg-1</a></li><li><span class=\"breadcrumbdivider\"></span><span>Add Sensor (Step 2 of 2)</span></li></ul></div>");
            builder.Append("<div class=\"add-sensor-main-container step-3\" id=\"main\" data-title=\"Add Sensor (Step 2 of 2)\" data-contexthelpshow=\"true\">");
            builder.Append("  <div class=\"add-sensor-box\">");
            builder.Append("    <div class=\"add-sensor-header\">");
            builder.Append("      <h1>");
            builder.Append("        <text><b>Add Sensor </b> to Device</text> <span data-id=\"2055\" class=\"to-device devicemenu localprobe hasred hasnopartialred hasack hasyellow hasnoorange hasblack hasblue hasgreen  isnotpaused  isnotfavorite\">ci-prtg-1 [ci-prtg-1]</span>");
            builder.Append("        <span class=\"steps\"> (Step 2 of 2)</span>");
            builder.Append("      </h1>");
            builder.Append("      <div class=\"eye-catcher\"></div>");
            builder.Append("      <div class=\"cancel-action\">");
            builder.Append("        <a onClick=\"history.back();return(false)\" class=\"btn cancel\">Cancel</a>");
            builder.Append("      </div>");
            builder.Append("    </div>");
            builder.Append("    <div id=\"content\">");
            builder.Append("      <form id=\"addobjectdialogform\" action=\"addsensor5.htm\" method=\"POST\" enctype=\"multipart/form-data\" class=\"prtg-form prtg-plugin formchanged\" data-plugin=\"prtg-form\" data-ajaxsubmit=\"true\">");
            builder.Append("          <fieldset>");
            builder.Append("<legend class=\"prtg-header\">Basic Sensor Settings</legend><div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"name_\">Sensor Name</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter a meaningful name to identify the sensor. By default, PRTG shows this name in the device tree, in alarms, logs, notifications, reports, maps, libraries, and tickets.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"name_\" id=\"name_\" autocomplete=\"off\" value=\"XML Custom EXE/Script Sensor\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"parenttags_\">Parent Tags</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"This field shows all tags that this object inherits from objects that are at a higher level in the hierarchy, like its parent device, its group and probe.<br/><br/> <b>Note:</b> The inheritance of tags cannot be disabled.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"parenttags_\" id=\"parenttags_\" autocomplete=\"off\" value=\"C_OS_VMware TestGroup TestProbe\" data-readonly=\"true\"></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"tags_\">Tags</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter a list of tags (not case sensitive) for filtering purposes (for example, the top 10 lists use these tags). Use spaces or commas as separators.<br/><br/> <b>Note:</b> Plus (+) or minus (-) are not allowed as first characters.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"tags_\" id=\"tags_\" autocomplete=\"off\" value=\"xmlexesensor\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"priority_\">Priority</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Define the priority status of this object. PRTG can sort this object in lists according to its priority, for example.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append("<select name=\"priority_\" class=\"combo\" id=\"priority_\" >");
            builder.Append("<option  value=\"5\" id=\"priority5\">***** (highest)</option>");
            builder.Append("<option  value=\"4\" id=\"priority4\">****</option>");
            builder.Append("<option  value=\"3\" selected=\"selected\"  id=\"priority3\">***</option>");
            builder.Append("<option  value=\"2\" id=\"priority2\">**</option>");
            builder.Append("<option  value=\"1\" id=\"priority1\">* (lowest)</option></select></div>");
            builder.Append("</div></fieldset><fieldset>");
            builder.Append("<legend class=\"prtg-header\">Sensor Settings</legend><div class=\"control-group\">");
            builder.Append("<div class=\"controls fillwidth\"><div class=\"controls-info\"><div class=\"readonlyproperty\" ><div><b>Important: The EXE file has to run on</b> the computer where <b>the parent probe</b> is installed, not on the parent device. The working directory for \"exe\" files is the probe directory, \"vbs,ps1\" or other script files may use different working directories.</div></div></div></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"exefile_\">EXE/Script</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select the executable or script file from the drop-down menu. Only files located in the <b>Custom Sensors\\EXEXML</b> sub-directory of the probe machine are listed.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#xmlexespecific'>Further Help (Manual)</a></p>\">");
            builder.Append("<select name=\"exefile_\" id=\"exefile_\" >");
            builder.Append("<option value=\"Demo Batchfile - Returns static values in four channels.bat|Demo Batchfile - Returns static values in four channels.bat||\" selected=\"selected\" >Demo Batchfile - Returns static values in four channels.bat</option>");
            builder.Append("<option value=\"testScript.bat|testScript.bat||\">testScript.bat</option></select></div>");
            builder.Append("<span class=\" InitialDisplayNone \"><div class=\"wiz1-3\"><input type=\"hidden\" name=\"exefilelabel\" value=\"\"></div></span>");
            builder.Append("<label class=\"control-label has_help \" for=\"exeparams_\">Parameters</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter command line parameters that the sensor will pass to the EXE/script file. 		  <br/><br/><b>Note:</b> Use quotation marks to escape the parameters correctly, for example, if the values contain blanks. With PowerShell scripts use single quotation marks, with all other scripts use double quotation marks.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#xmlexespecific'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"exeparams_\" id=\"exeparams_\" autocomplete=\"off\" value=\"\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"environment_\">Environment</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Define if commandline parameters of PRTG will be also available as environment parameters. Use this option carefully, there can be security issues with this option.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#xmlexespecific'>Further Help (Manual)</a></p>\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"environment_\" value=\"0\" checked  id=\"environment0\" >");
            builder.Append("<label for=\"environment0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Default Environment");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"environment_\" value=\"1\" id=\"environment1\" >");
            builder.Append("<label for=\"environment1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Set placeholders as environment values");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<label class=\"control-label has_help \" for=\"usewindowsauthentication_\">Security Context</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Choose a security context to run the EXE/script file.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#xmlexespecific'>Further Help (Manual)</a></p>\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"usewindowsauthentication_\" value=\"0\" checked  id=\"usewindowsauthentication0\" >");
            builder.Append("<label for=\"usewindowsauthentication0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Use security context of probe service");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"usewindowsauthentication_\" value=\"1\" id=\"usewindowsauthentication1\" >");
            builder.Append("<label for=\"usewindowsauthentication1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Use Windows credentials of parent device");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<label class=\"control-label has_help \" for=\"mutexname_\">Mutex Name</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter a mutex. All EXE/Script sensors that have the same mutex name will be executed serially (not simultaneously). This is useful if you have a lot of sensors and want to avoid high resource usage caused by processes running simultaneously.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#xmlexespecific'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"mutexname_\" id=\"mutexname_\" autocomplete=\"off\" value=\"\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"timeout_\">Timeout (Sec.)</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Define a timeout. The external process will be killed if it does not return a result in this time.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#xmlexespecific'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  data-rule-number=\"true\" data-rule-max=\"900\" data-rule-min=\"1\" data-rule-required=\"true\" type=\"text\" name=\"timeout_\" id=\"timeout_\" autocomplete=\"off\" value=\"60\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"writeresult_\">EXE Result</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Define if the EXE result will be stored (Filename: 'Result of Sensor [ID].txt'). If enabled, a text file with the last response will be stored in the <b>Logs (Sensors)</b> directory (on the computer running the probe).<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#xmlexespecific'>Further Help (Manual)</a></p>\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"writeresult_\" value=\"0\" checked  id=\"writeresult0\" >");
            builder.Append("<label for=\"writeresult0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Discard EXE result");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"writeresult_\" value=\"1\" id=\"writeresult1\" >");
            builder.Append("<label for=\"writeresult1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Write EXE result to disk");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"writeresult_\" value=\"2\" id=\"writeresult2\" >");
            builder.Append("<label for=\"writeresult2\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Write EXE result to disk in case of error");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("</div></fieldset><fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\">Scanning Interval");
            builder.Append("<span class=\"inheritedfrom\">");
            builder.Append("<input name=\"intervalgroup\" type=\"hidden\" value=\"0\"><input class=\"toggleFieldset GroupShowHide checkbox\" name=\"intervalgroup\" type=\"checkbox\" value=\"1\" id=\"Inheritintervalgroup\"  checked=\"checked\" ><label for=\"Inheritintervalgroup\"data-placement=\"right\" data-helptext=\"Clicking <b>inherit from</b> breaks the inheritance and allows you to make your own settings. Clicking it again reverts back to the inheritance and overrides your settings.\"\">inherit from</label> <a  dependency=\"2056\" deptype=\"select\"  thisid=\"2055\" class=\"devicemenu isnotpaused  isnotfavorite localprobe\" style=\"background-image:url(/icons/devices/C_OS_VMware.png?svg)\" id=\"2055\" href=\"device.htm?id=2055\">ci-prtg-1</a> ");
            builder.Append(" <span title=\"Scanning Interval: 60 seconds, Set sensor to warning for 1 interval, then set to &quot;down&quot; (recommended)\">(Scanning Interval: 60 seconds, Set sensor to ...)</span></span>");
            builder.Append("</legend><div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"interval_\">Scanning Interval</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select the period of time between two scans.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#intervalgroup'>Further Help (Manual)</a></p>\">");
            builder.Append("<select name=\"interval_\" id=\"interval_\" >");
            builder.Append("<option value=\"5|5 seconds (Not officially supported)\">5 seconds (Not officially supported)</option>");
            builder.Append("<option value=\"10|10 seconds\">10 seconds</option>");
            builder.Append("<option value=\"30|30 seconds\">30 seconds</option>");
            builder.Append("<option value=\"60|60 seconds\" selected=\"selected\" >60 seconds</option>");
            builder.Append("<option value=\"300|5 minutes\">5 minutes</option>");
            builder.Append("<option value=\"600|10 minutes\">10 minutes</option>");
            builder.Append("<option value=\"900|15 minutes\">15 minutes</option>");
            builder.Append("<option value=\"1800|30 minutes\">30 minutes</option>");
            builder.Append("<option value=\"3600|1 hour\">1 hour</option>");
            builder.Append("<option value=\"14400|4 hours\">4 hours</option>");
            builder.Append("<option value=\"21600|6 hours\">6 hours</option>");
            builder.Append("<option value=\"43200|12 hours\">12 hours</option>");
            builder.Append("<option value=\"86400|24 hours\">24 hours</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"errorintervalsdown_\">If a Sensor Query Fails</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"If a sensor query fails, for example, because the monitored device is unreachable, PRTG can try to reach and check the device again within the next scanning interval before the sensor is shown as 'down'. This can avoid false alarms if your device has temporary issues only.<br/><br/><b>Note:</b> WMI sensors always use at least 1 interval. Channel error limits and channels using lookups will always set the sensor to 'down' immediately.<p><a class='morehelp nohjax' target='_blank' href='/help/exe_script_advanced_sensor.htm#intervalgroup'>Further Help (Manual)</a></p>\">");
            builder.Append("<select name=\"errorintervalsdown_\" class=\"combo\" id=\"errorintervalsdown_\" >");
            builder.Append("<option  value=\"0\" id=\"errorintervalsdown0\">Set sensor to &quot;down&quot; immediately</option>");
            builder.Append("<option  value=\"1\" selected=\"selected\"  id=\"errorintervalsdown1\">Set sensor to warning for 1 interval, then set to &quot;down&quot; (recommended)</option>");
            builder.Append("<option  value=\"2\" id=\"errorintervalsdown2\">Set sensor to warning for 2 intervals, then set to &quot;down&quot;</option>");
            builder.Append("<option  value=\"3\" id=\"errorintervalsdown3\">Set sensor to warning for 3 intervals, then set to &quot;down&quot;</option>");
            builder.Append("<option  value=\"4\" id=\"errorintervalsdown4\">Set sensor to warning for 4 intervals, then set to &quot;down&quot;</option>");
            builder.Append("<option  value=\"5\" id=\"errorintervalsdown5\">Set sensor to warning for 5 intervals, then set to &quot;down&quot;</option></select></div>");
            builder.Append("<span class=\" InitialDisplayNone \"><div class=\"wiz1-3\"><input type=\"hidden\" name=\"inherittriggers\" value=\"1\"></div></span>");
            builder.Append("</div></fieldset><input type=\"hidden\" name=\"id\" value=\"2055\"> <input type=\"hidden\" name=\"sensortype\" value=\"exexml\">");
            builder.Append("		  <input type=\"hidden\" id=\"tmpid\" name=\"tmpid\" value=\"2\">");
            builder.Append("          <div style='' class=\"quick-action-wrapper \">");
            builder.Append("              <button style='' class=\"submit btngrey button quick-action-button force-visible\" type=\"submit\">Continue</button>");
            builder.Append("              <button style='' type=\"submit\" class='ui-icon quick-action-badge continue-badge'></button>");
            builder.Append("          </div>");
            builder.Append("      </form>");
            builder.Append("    </div>");
            builder.Append("  </div>");
            builder.Append("  ");
            builder.Append("  ");
            builder.Append("  ");
            builder.Append("  ");
            builder.Append("  ");
            builder.Append("  ");
            builder.Append("  ");
            builder.Append("  ");
            builder.Append("  <div class=\"contexthelpbox prtg-plugin\" data-id=\"id1169398716\" data-plugin=\"contexthelp\" data-plugin-function=\"add\" data-plugin-target=\"#header_help\" data-show=\"true\"><div class=\"helpheader\">Specifying sensor settings</div><p>Please specify the settings for the new sensor. <a href='/help/exe_script_advanced_sensor.htm#settings' target='_blank'><b>Help: Sensor Settings</b></a></p></div>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<tct");
            builder.Append("  data-role=\"action\"");
            builder.Append("  data-page=\"facelift-update\">");
            builder.Append("<div id=\"facelift-dialogcontent\" class=\"js-facelift-dialogcontent\" data-dialog-title=\"What’s New in PRTG\">");
            builder.Append("    <h1>Major UI Improvements</h1>");
            builder.Append("    <div class=\"js-slider\">");
            builder.Append("        <div class=\"slide\">");
            builder.Append("            <p class=\"media-content\">");
            builder.Append("                <span>Welcome to the all-new web interface of PRTG! We have tidied up PRTG and given it a cleaner look so you can find what you need more easily.</span>");
            builder.Append("            </p>");
            builder.Append("            <p class=\"media-content bordered\">");
            builder.Append("                <span class=\"overlay-text\">");
            builder.Append("                    This PRTG version includes many improvements to the look and feel of the UI. For example, <strong>Add</strong> buttons in the device tree have been bundled into one central location for ease of use.");
            builder.Append("                    Click <i class=\"glyph-plus-circled\"></i> to open the new <strong>Add</strong> menu.</span>");
            builder.Append("                <img src=\"./images/17.3.34-add_menu1.png\" >");
            builder.Append("                <span class=\"image-caption\">New Add Sensor Buttons in the Device Tree</span>");
            builder.Append("            </p>");
            builder.Append("        </div>");
            builder.Append("        <div class=\"slide\">");
            builder.Append("            <p class=\"media-content bordered\">");
            builder.Append("                <span>");
            builder.Append("                        <img src=\"./images/17.3.34-multi-edit.png\" >");
            builder.Append("                        <span class=\"image-caption\">Editing in Table Lists with Multi-Edit</span>");
            builder.Append("                </span>");
            builder.Append("                <span class=\"overlay-text\">");
            builder.Append("                    The <strong>Edit</strong> function in table lists now always works like the former <strong>Multi-Edit</strong> function. Select the object/s you want to edit and the menu appears to the right.");
            builder.Append("                </span>");
            builder.Append("            </p>");
            builder.Append("        </div>");
            builder.Append("        <div class=\"slide\">");
            builder.Append("            <p class=\"media-content bordered\">");
            builder.Append("                <span>");
            builder.Append("                        <img src=\"./images/17.3.34-floating-save.png\" >");
            builder.Append("                        <span class=\"image-caption\">New Floating Save Button in Forms</span>");
            builder.Append("                </span>");
            builder.Append("                <span class=\"overlay-text\">");
            builder.Append("                    Forms now have a floating <strong>Save</strong> button in the bottom right corner. The button turns blue once you have made changes and you can save at any time.");
            builder.Append("                </span>");
            builder.Append("            </p>");
            builder.Append("        </div>");
            builder.Append("        <div class=\"slide\">");
            builder.Append("            <p class=\"media-content bordered\">");
            builder.Append("                <span>");
            builder.Append("                        <img src=\"./images/17.3.34-table-filter.png\" >");
            builder.Append("                        <span class=\"image-caption\">New Show/Hide Filters Function</span>");
            builder.Append("                </span>");
            builder.Append("                <span class=\"overlay-text\">");
            builder.Append("                    Table lists now have separate filters that you can hide or show.");
            builder.Append("                </span>");
            builder.Append("            </p>");
            builder.Append("        </div>");
            builder.Append("        <div class=\"slide\">");
            builder.Append("            <p class=\"media-content bordered\">");
            builder.Append("                <span>");
            builder.Append("                        <img src=\"./images/17.3.34-object-selector.png\" >");
            builder.Append("                        <span class=\"image-caption\">New Object Selector for Device Tree Object Submenus</span>");
            builder.Append("                </span>");
            builder.Append("                <span class=\"overlay-text\">");
            builder.Append("                 The submenus for device tree objects in the main menu bar have been removed and the respective pages now have a new object selector.");
            builder.Append("                </span>");
            builder.Append("            </p>");
            builder.Append("        </div>");
            builder.Append("        <div class=\"slide\">");
            builder.Append("            <div class=\"text-big js-adjustToHeight\">");
            builder.Append("                <p>");
            builder.Append("                    These are just a few of the improvements we have made.<br/> For more information, please see the <a class=\"arrow\" target=\"_blank\" href=\"/help/introduction.htm\">manual</a> or our");
            builder.Append("                    <a class=\"arrow\" target=\"_blank\" href=\"https://blog.paessler.com/all\">blog</a>.<br/> Enjoy!");
            builder.Append("                </p>");
            builder.Append("            </div>");
            builder.Append("        </div>");
            builder.Append("    </div>");
            builder.Append("</div>");
            builder.Append("</tct>");
            builder.Append("    <footer class=\"hidebuttons\">");
            builder.Append("        <div id='alarmsound'></div>");
            builder.Append("        <div id=\"prtg_growls\" class=\"growls\"></div>");
            builder.Append("        <div id='helpcontainer' class=\"prtg-plugin footer_help hidden\" data-plugin=\"contexthelp\">");
            builder.Append("            <div class=\"footer_help-box\">");
            builder.Append("                <div class=\"helptitle\">");
            builder.Append("                    <span class=\"glyph-help-circled\"></span>");
            builder.Append("                    Help<i id=\"closehelp\" class=\"flr glyph-cancel-1\"></i>");
            builder.Append("                </div>");
            builder.Append("                <div class=\"lasthelpitem contexthelpbox\">");
            builder.Append("                    <div class=\"helpmorehelp\">");
            builder.Append("                        <a href='/help.htm'>Get more help in the Help Center!</a>");
            builder.Append("                    </div>");
            builder.Append("                </div>");
            builder.Append("            </div>");
            builder.Append("        </div>");
            builder.Append("        <div class=\"footer\">");
            builder.Append("            <a class=\"footer_logo\" href=\"https://www.paessler.com\" target=\"_blank\" id=\"paesslerlogo\" title=\"Paessler AG - The Network Monitoring Company\"></a>");
            builder.Append("            <span class=\"footer_version\">17.4.35.3441  </span>");
            builder.Append("            <span class=\"footer_user\">PRTG System Administrator</span>");
            builder.Append("            <span class=\"js-servertime servertimebox\" title='9/01/2018 4:19:01 PM (UTC+10:00)' data-placement=\"top\" data-timezone='UTC+10:00'>");
            builder.Append("                <i class=\"glyph-clock\"></i>");
            builder.Append("                <span class=\"serverclock\">4:19:01 PM</span>");
            builder.Append("            </span>");
            builder.Append("            <span id='footerrefresh' class=\"prtg-plugin footer_datetime\" data-plugin=\"prtg-toggle-autorefresh\">");
            builder.Append("                <span class=\"refreshclock\"><a class=\"toggle-autorefresh\" href=\"#\"><i class=\"icon-pause icon-dark\"></i></a></span>");
            builder.Append("                <span class=\"refreshclock\">Refresh in</span>");
            builder.Append("                <span class=\"refreshclock\" id=\"footerrefreshclock\">30</span>");
            builder.Append("                <span class=\"refreshclock\">sec</span>");
            builder.Append("                <span class=\"refreshinglable\">Refreshing...</span>");
            builder.Append("            </span>");
            builder.Append("        </div>");
            builder.Append("        <div id=\"sendfeedbackbox\" class=\"footerButtons\">");
            builder.Append("            ");
            builder.Append("            <a id=\"updatevailablebox\" class=\"footerButtons-update\" onclick=\"window.top.location.href = '/autoupdate.htm';return false;\"");
            builder.Append("               style='  display:none'>");
            builder.Append("                <i class=\"icon-gear icon-dark\"></i> Update Available");
            builder.Append("            </a>");
            builder.Append("            <a href=\"#\" class=\"js-livechat_button\" style=\"display: none\"> <i class=\"glyph-bubbles3\"></i>Live Chat</a>");
            builder.Append("            <a id=\"sendfeedback\" class=\"hidefeedbackbutton\" style=\" display:none; \"");
            builder.Append("               onclick=\"_Prtg.objectTools.sendFeedback('/sendfeedback.htm?errorurl='+window.location.pathname,'');return false;\">");
            builder.Append("                <i class=\"icon-mail-closed icon-dark\"></i>Contact Support");
            builder.Append("            </a>");
            builder.Append("            <a id=\"togglehelp\">");
            builder.Append("                <i class=\"icon-help icon-dark\"></i>");
            builder.Append("                    Help");
            builder.Append("                <span class=\"helpactive\" style=\"display: inline-block;\"></span>");
            builder.Append("            </a>");
            builder.Append("        </div>");
            builder.Append("    </footer>");
            builder.Append("<noscript>");
            builder.Append("  <div class=\"ui-widget-overlay ui-front\"></div>");
            builder.Append("  <div id=\"nojavascripterror\">");
            builder.Append("    <b>Sorry, the AJAX Web Interface of PRTG can not work properly without Javascript.</b><br><br><i>Javascript seems to be disabled or this browser does not support Javascript.</i><br><br>Please enable Javascript");
            builder.Append("  </div>");
            builder.Append("</noscript>");
            builder.Append("<script src='/javascript/prtg.js?version=17.4.35.3441&language=en'></script>");
            builder.Append("</body>");
            builder.Append("</html>");

            return builder.ToString();
        }
    }
}
