using System.Linq;
using System.Text;
using System.Xml.Linq;
using PrtgAPI.Helpers;
using PrtgAPI.Tests.UnitTests.ObjectTests.TestItems;

namespace PrtgAPI.Tests.UnitTests.ObjectTests.TestResponses
{
    static class PrtgClientExtensions
    {
        public static Group AddGroup(this PrtgClient client, int parentId, string name)
        {
            client.AddGroup(parentId, name);
            return client.GetGroups(new SearchFilter(Property.ParentId, parentId), new SearchFilter(Property.Name, name)).First();
        }
    }

    public class NotificationActionResponse : BaseResponse<NotificationActionItem>
    {
        internal NotificationActionResponse(params NotificationActionItem[] notifications) : base("notifications", notifications)
        {
        }

        string GetSettingsResponseText(string address)
        {
            var components = UrlHelpers.CrackUrl(address);

            var item = items.FirstOrDefault(i => i.ObjId == components["id"]);

            var builder = new StringBuilder();
            
            builder.Append("<form id=\"editnotificationform\" enctype=\"multipart/form-data\" action=\"/editsettings\" method=\"post\" class=\"prtg-form prtg-plugin\" data-plugin=\"prtg-form\" data-ajaxsubmit=\"true\">");
            builder.Append("    <div class=\"cancel-action\">");
            builder.Append("        <a onClick=\"history.back();return(false)\" class=\"btn cancel\" type=\"reset\">Cancel</a>");
            builder.Append("    </div>");
            builder.Append("    <fieldset>");
            builder.Append("<legend class=\"prtg-header\">Basic Notification Settings</legend><div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"name_\">Notification Name</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter a meaningful name for the notification.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"name_\" id=\"name_\" autocomplete=\"off\" value=\"Email to all members of group PRTG Users Group\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"tags_\">Tags</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter a list of tags (not case sensitive) for filtering purposes (for example, the top 10 lists use these tags). Use spaces or commas as separators.<br/><br/> <b>Note:</b> Plus (+) or minus (-) are not allowed as first characters.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append($"<input class=\"text\"  type=\"text\" name=\"tags_\" id=\"tags_\" autocomplete=\"off\" value=\"{item?.Tags ?? "testTag1 testTag2"}\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"active_\">Status</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Use <b>Paused</b> to temporarily disable this notification. PRTG only sends messages when the status of the notification is <b>Started</b>.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"active_\" value=\"1\" checked  id=\"active1\" >");
            builder.Append("<label for=\"active1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Started");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"active_\" value=\"0\" id=\"active0\" >");
            builder.Append("<label for=\"active0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Paused");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<label class=\"control-label has_help \" for=\"schedule_\">Schedule</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Use schedules to only activate notifications within specific time spans (days, hours) throughout the week. You can edit schedules in the account settings.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append("<select name=\"schedule_\" id=\"schedule_\" >");
            builder.Append("<option value=\"-1|None|\" selected=\"selected\" >None</option>");
            builder.Append("<option value=\"623|Saturdays [GMT+1100]|\">Saturdays [GMT+1100]</option>");
            builder.Append("<option value=\"622|Sundays [GMT+1100]|\">Sundays [GMT+1100]</option>");
            builder.Append("<option value=\"620|Weekdays [GMT+1100]|\">Weekdays [GMT+1100]</option>");
            builder.Append("<option value=\"625|Weekdays Eight-To-Eight (8:00 - 20:00) [GMT+1100]|\">Weekdays Eight-To-Eight (8:00 - 20:00) [GMT+1100]</option>");
            builder.Append("<option value=\"627|Weekdays Nights (17:00 - 9:00) [GMT+1100]|\">Weekdays Nights (17:00 - 9:00) [GMT+1100]</option>");
            builder.Append("<option value=\"626|Weekdays Nights (20:00 - 8:00) [GMT+1100]|\">Weekdays Nights (20:00 - 8:00) [GMT+1100]</option>");
            builder.Append("<option value=\"624|Weekdays Nine-To-Five (9:00 - 17:00) [GMT+1100]|\">Weekdays Nine-To-Five (9:00 - 17:00) [GMT+1100]</option>");
            builder.Append("<option value=\"621|Weekends [GMT+1100]|\">Weekends [GMT+1100]</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"postpone_\">Postpone</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Define what PRTG does when this notification is triggered during paused status. Choose to collect all notifications that are triggered during a scheduled pause to receive them after the pause ends. 			Otherwise, PRTG discards all messages during the pause.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#basic'>Further Help (Manual)</a></p>\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"postpone_\" value=\"0\" id=\"postpone0\" >");
            builder.Append("<label for=\"postpone0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Discard notifications during paused status");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"postpone_\" value=\"1\" checked  id=\"postpone1\" >");
            builder.Append("<label for=\"postpone1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Collect notifications and send them when reactivated");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<span class=\" InitialDisplayNone \"><div class=\"wiz1-3\"><input type=\"hidden\" name=\"comments\" value=\"test\"></div></span>");
            builder.Append("</div></fieldset><fieldset>");
            builder.Append("<legend class=\"prtg-header\">Notification Summarization</legend><div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"summode_\">Method</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Use summarization to avoid message floods. The first option does not summarize notifications at all, but will always send messages immediately.<br/><br/> 		  <b>Note:</b> PRTG will send out the summarized message as soon as 25 notifications are collected or when the timespan runs out, whichever occurs first. If PRTG triggers more than 25 notifications, you will receive more than one summarization with up to 25 entries each.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#summarization'>Further Help (Manual)</a></p>\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"summode_\" value=\"0\" id=\"summode0\" >");
            builder.Append("<label for=\"summode0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Always notify ASAP, never summarize");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"summode_\" value=\"1\" id=\"summode1\" >");
            builder.Append("<label for=\"summode1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Send first DOWN message ASAP, then summarize");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"summode_\" value=\"2\" checked  id=\"summode2\" >");
            builder.Append("<label for=\"summode2\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Send first DOWN and UP message ASAP, then summarize");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"summode_\" value=\"3\" id=\"summode3\" >");
            builder.Append("<label for=\"summode3\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Send all DOWN messages ASAP, summarize the others");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"summode_\" value=\"4\" id=\"summode4\" >");
            builder.Append("<label for=\"summode4\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Send all DOWN and UP messages ASAP, summarize the others");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"summode_\" value=\"5\" id=\"summode5\" >");
            builder.Append("<label for=\"summode5\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Always summarize messages, regardless of type");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<label class=\"control-label has_help \" for=\"summarysubject_\">Subject for Summarized Email or SNS Messages</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"This subject is attached when sending summarized messages. Use %SUMMARYCOUNT as placeholder for the number of messages that were summarized. <br/><br/> <b>Note:</b> Subjects are only used for email and Amazon SNS messages.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#summarization'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"summarysubject_\" id=\"summarysubject_\" autocomplete=\"off\" value=\"[%sitename] %summarycount Summarized Notifications\" ></div>");
            builder.Append("<label class=\"control-label has_help  Showsummode1  Showsummode2  Showsummode3  Showsummode4  Showsummode5  Hidesummode0  groupshowhideelement\" for=\"summinutes_\">Timespan for Summarizing Messages (in Minutes)</label>");
            builder.Append("<div class=\"controls  Showsummode1  Showsummode2  Showsummode3  Showsummode4  Showsummode5  Hidesummode0  groupshowhideelement\" data-placement=\"right\" data-helptext=\"Enter how long (in minutes) PRTG collects notifications until it sends out a summarized message.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#summarization'>Further Help (Manual)</a></p>\">");
            builder.Append("<input class=\"text\"  data-rule-number=\"true\" type=\"text\" name=\"summinutes_\" id=\"summinutes_\" autocomplete=\"off\" value=\"1\" ></div>");
            builder.Append("</div></fieldset><fieldset>");
            builder.Append("<legend class=\"prtg-header\">Access Rights</legend><div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"accessrights_\">User Group Access</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Set user group access rights for this monitoring object. You cannot remove the rights defined for the parent node of this object. All the rights you define here are inherited to all child nodes of this object.<p><a class='morehelp nohjax' target='_blank' href='/help/notifications_settings.htm#accessgroup'>Further Help (Manual)</a></p>\">");
            builder.Append("<table class=\"table hoverable\" ><thead><tr><th>User Group<input type=\"hidden\" name=\"accessrights_\" value=\"1\"></th><th>Rights</th></tr></thead><tr class=\"even\"><td><div class=\"unitselect\">PRTG Users Group</div></td><td><select class=\"rightsselect\" name=\"accessrights_201\" id=\"accessrights_\" ><option value=\"0\">None</option><option value=\"100\" selected=\"selected\" >Read</option><option value=\"200\">Write</option><option value=\"400\">Full</option></select></td></tr></table></div>");
            builder.Append("</div></fieldset><fieldset>");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_1\" type=\"hidden\" value=\"0\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_1\" id=\"active_1\" value=\"1\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_1\" >Send Email</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label no_help \" for=\"EMail\"></label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" >");
            builder.Append("<div class=\"readonlyproperty\" >The three recipient settings below (user, user group, email address) work independently. So every contact and address selected by any of these settings will receive the notification.</div></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EMail\">Send to User</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select a user from the list. PRTG sends the notification to every active email contact of the selected user. Select <b>None</b> to not use this option. <br/><br/><b>Note:</b> Use the options <b>Send to User</b>, <b>Send to User Group</b>, and <b>Send to Email Address</b> simultaneously to send this notification to all defined recipients at the same time.\">");
            builder.Append("<select name=\"addressuserid_1\" id=\"addressuserid_1\" >");
            builder.Append("<option value=\"-1\"  selected=\"selected\" >None</option>");
            builder.Append("<option value=\"100|PRTG System Administrator|\">PRTG System Administrator</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EMail\">Send to User Group</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select a user group from the list. PRTG sends the notification to every active email contact of every user in the selected group. Select <b>None</b> to not use this option. <br/><br/><b>Note:</b> Use the options <b>Send to User</b>, <b>Send to User Group</b>, and <b>Send to Email Address</b> simultaneously to send this notification to all defined recipients at the same time.\">");
            builder.Append("<select name=\"addressgroupid_1\" id=\"addressgroupid_1\" >");
            builder.Append("<option value=\"-1\" >None</option>");
            builder.Append("<option value=\"200|PRTG Administrators|400|0|1|\">PRTG Administrators</option>");
            builder.Append("<option value=\"201|PRTG Users Group|100|0|0|\" selected=\"selected\" >PRTG Users Group</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EMail\">Send to Email Address</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter one or more comma separated email addresses. PRTG sends the notification to all addresses that you enter here. Leave the field empty to not use this option. <br/><br/><b>Note:</b> Use the options <b>Send to User</b>, <b>Send to User Group</b>, and <b>Send to Email Address</b> simultaneously to send this notification to all defined recipients at the same time.\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"address_1\" id=\"address_1\" autocomplete=\"off\" value=\"test@example.com\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EMail\">Subject</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the subject part of the email.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"subject_1\" id=\"subject_1\" autocomplete=\"off\" value=\"[%sitename] %device %name %status %down (%message)\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EMail\">Format</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Choose if you want to use the default HTML or text templates for notifications or if you want to use a custom text.\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"contenttype_1\" value=\"text/html\" id=\"contenttypetexthtml\" >");
            builder.Append("<label for=\"contenttypetexthtml\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("HTML");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"contenttype_1\" value=\"text/plain\" checked id=\"contenttypetextplain\" >");
            builder.Append("<label for=\"contenttypetextplain\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Text");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"contenttype_1\" value=\"text/custom\" id=\"contenttypetextcustom\" >");
            builder.Append("<label for=\"contenttypetextcustom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Text with custom content");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<span id=\"customcontenton\" class=\" Showcontenttypetextcustom  Hidecontenttypetexthtml  InitialDisplayNone  Hidecontenttypetextplain  groupshowhideelement\">");
            builder.Append("<label class=\"control-label has_help \" for=\"EMail\">Custom Content</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter custom content for your text notification. You can use notification placeholders here.\">");
            builder.Append("<textarea class=\"textarea\"  id=\"customtext_1\" name=\"customtext_1\" rows=\"2\" >grumpy wizards make toxic brew</textarea></div>");
            builder.Append("</span>");
            builder.Append("<label class=\"control-label has_help \" for=\"EMail\">Priority</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Define the priority for the email.\">");
            builder.Append("<select name=\"priority_1\" class=\"combo\" id=\"priority_1\" >");
            builder.Append("<option  value=\"0\" id=\"priority0\">highest</option>");
            builder.Append("<option  value=\"1\" selected=\"selected\" id=\"priority1\">high</option>");
            builder.Append("<option  value=\"2\" id=\"priority2\">normal</option>");
            builder.Append("<option  value=\"3\" id=\"priority3\">low</option>");
            builder.Append("<option  value=\"4\" id=\"priority4\">lowest</option></select></div>");
            builder.Append("</div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_17\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_17\" id=\"active_17\" value=\"17\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_17\" >Send Push Notification<sup>BETA</sup></label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label no_help \" for=\"Push\"></label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" >");
            builder.Append("<div class=\"readonlyproperty\" >The two recipient settings below (user, user group) work independently. So every push device selected by any of these settings will receive the notification.</div></div>");
            builder.Append("<label class=\"control-label no_help \" for=\"Push\"></label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" >");
            builder.Append("<div class=\"readonlyproperty\" ><b>Note:</b> The PRTG server must be able to reach the PRTG cloud on TCP port 443 to send push notifications.</div></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"Push\">Send to a User</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select a user to which push notifications are to be sent. Every active push device of the selected user will receive the notification.\">");
            builder.Append("<select name=\"addressuserid_17\" id=\"addressuserid_17\" >");
            builder.Append("<option value=\"-1\"  selected=\"selected\" >None</option>");
            builder.Append("<option value=\"100|PRTG System Administrator|\">PRTG System Administrator</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"Push\">Send to a User Group</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select a user group to which push notifications are to be sent. Every active push device of every user in the selected user group will receive the notification.\">");
            builder.Append("<select name=\"addressgroupid_17\" id=\"addressgroupid_17\" >");
            builder.Append("<option value=\"-1\"  selected=\"selected\" >None</option>");
            builder.Append("<option value=\"200|PRTG Administrators|400|0|1|\">PRTG Administrators</option>");
            builder.Append("<option value=\"201|PRTG Users Group|100|0|0|\">PRTG Users Group</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"Push\">Message</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"The message to be sent (<a href='http://kb.paessler.com/en/topic/373' target='blank'>placeholders</a> allowed).<br/><br/><b>Note:</b> Enter a single * character (and nothing else) if you want to reset this field to the system default.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"message_17\" id=\"message_17\" autocomplete=\"off\" value=\"[%sitename] %device %name %status %down (%message)\" ></div>");
            builder.Append("</div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_8\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_8\" id=\"active_8\" value=\"8\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_8\" >Send SMS/Pager Message</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label no_help \" for=\"SMS\"></label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" >");
            builder.Append("<div class=\"readonlyproperty\" >The three recipient settings below (user, user group, recipient number) work independently. So every contact/address selected by any of these settings will receive the notification</div></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SMS\">Send to User</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select a user from the list. PRTG sends the notification to every active SMS contact of the selected user. Select 'None' to not use this option. <br/><br/><b>Note:</b> Use the options <b>Send to User</b>, <b>Send to User Group</b>, and <b>Send to Number</b> simultaneously to send this notification to all defined recipients at the same time.\">");
            builder.Append("<select name=\"addressuserid_8\" id=\"addressuserid_8\" >");
            builder.Append("<option value=\"-1\"  selected=\"selected\" >None</option>");
            builder.Append("<option value=\"100|PRTG System Administrator|\">PRTG System Administrator</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SMS\">Send to User Group</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select a user group from the list. PRTG sends the notification to every active SMS contact of every user in the selected group. Select 'None' to not use this option. <br/><br/><b>Note:</b> Use the options <b>Send to User</b>, <b>Send to User Group</b>, and <b>Send to Number</b> simultaneously to send this notification to all defined recipients at the same time.\">");
            builder.Append("<select name=\"addressgroupid_8\" id=\"addressgroupid_8\" >");
            builder.Append("<option value=\"-1\"  selected=\"selected\" >None</option>");
            builder.Append("<option value=\"200|PRTG Administrators|400|0|1|\">PRTG Administrators</option>");
            builder.Append("<option value=\"201|PRTG Users Group|100|0|0|\">PRTG Users Group</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SMS\">Send to Number</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter one or more comma separated phone numbers. The format depends on your SMS provider. Usual rules are: Start phone numbers with '+', followed by the country code. Do not use spaces in phone numbers. <b>Note:</b> Double-check the number format with the requirements of your SMS provider. A number in the wrong format may result in undelivered messages!<br/><br/>PRTG sends the notification to all numbers you enter here. Leave the field empty to not use this option. <br/><br/><b>Note:</b> Use the options <b>Send to User</b>, <b>Send to User Group</b>, and <b>Send to Number</b> simultaneously to send this notification to all defined recipients at the same time.\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"address_8\" id=\"address_8\" autocomplete=\"off\" value=\"1234567890\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SMS\">Message</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"The message to be sent (<a href='http://kb.paessler.com/en/topic/373' target='blank'>placeholders</a> allowed).<br/><br/><b>Note:</b> Enter a single * character (and nothing else) if you want to reset this field to the system default.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"message_8\" id=\"message_8\" autocomplete=\"off\" value=\"[%sitename] %device %name %status %down (%message)\" ></div>");
            builder.Append("<label class=\"control-label no_help \" for=\"\"></label><div class=\"controls\"><div class=\"readonlyproperty\">Please note: <b>SMS</b> has <b>not</b> been configured in the <b><a href=\"/systemsetup.htm?tabid=3\">System Setup</a></b> yet.</div></div></div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_2\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_2\" id=\"active_2\" value=\"2\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_2\" >Add Entry to Event Log</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"event\">Logfile</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select the logfile.\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"eventlogfile_2\" value=\"application\" id=\"eventlogfileapplication\" >");
            builder.Append("<label for=\"eventlogfileapplication\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Application");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"eventlogfile_2\" value=\"internal\" checked id=\"eventlogfileinternal\" >");
            builder.Append("<label for=\"eventlogfileinternal\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("PRTG Network Monitor");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<span id=\"eventlogdependencyon\" class=\" Showeventlogfileapplication  Hideeventlogfileinternal  groupshowhideelement\">");
            builder.Append("<label class=\"control-label has_help \" for=\"event\">Event Source</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the 'source' for the event (usually the name of the application).<br/>This value will be ignored if you choose <b>PRTG Network Monitor</b> as logfile.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"sender_2\" id=\"sender_2\" autocomplete=\"off\" value=\"PRTG Network Monitor\" ></div>");
            builder.Append("</span>");
            builder.Append("<label class=\"control-label has_help \" for=\"event\">Event Type</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select the event type\">");
            builder.Append("<select name=\"eventtype_2\" class=\"combo\" id=\"eventtype_2\" >");
            builder.Append("<option  value=\"error\" id=\"eventtypeerror\">Error</option>");
            builder.Append("<option  value=\"warning\" id=\"eventtypewarning\" selected=\"selected\">Warning</option>");
            builder.Append("<option  value=\"information\" id=\"eventtypeinformation\">Information</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"event\">Event Log Message</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"The message to be sent (<a href='http://kb.paessler.com/en/topic/373' target='blank'>placeholders</a> allowed).<br/><br/><b>Note:</b> Enter a single * character (and nothing else) if you want to reset this field to the system default.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"message_2\" id=\"message_2\" autocomplete=\"off\" value=\"[%sitename] %device %name %status %down (%message)\" ></div>");
            builder.Append("</div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_13\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_13\" id=\"active_13\" value=\"13\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_13\" >Send Syslog Message</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"Syslog\">Host/IP</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the IP address or DNS name of the computer that runs the syslog server\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"sysloghost_13\" id=\"sysloghost_13\" autocomplete=\"off\" value=\"localhost\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"Syslog\">Syslog Port</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the syslog port of the device. Standard is 514.\">");
            builder.Append("<input class=\"text\"  data-rule-number=\"true\" data-rule-required=\"true\" type=\"text\" name=\"syslogport_13\" id=\"syslogport_13\" autocomplete=\"off\" value=\"514\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"Syslog\">Facility</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Choose the facility of the syslog message.\">");
            builder.Append("<select name=\"syslogfacility_13\" class=\"combo\" id=\"syslogfacility_13\" >");
            builder.Append("<option  value=\"1\" id=\"syslogfacility1\">User-level messages</option>");
            builder.Append("<option  value=\"16\" id=\"syslogfacility16\">Local use 0</option>");
            builder.Append("<option  value=\"17\" id=\"syslogfacility17\">Local use 1</option>");
            builder.Append("<option  value=\"18\" id=\"syslogfacility18\" selected=\"selected\">Local use 2</option>");
            builder.Append("<option  value=\"19\" id=\"syslogfacility19\">Local use 3</option>");
            builder.Append("<option  value=\"20\" id=\"syslogfacility20\">Local use 4</option>");
            builder.Append("<option  value=\"21\" id=\"syslogfacility21\">Local use 5</option>");
            builder.Append("<option  value=\"22\" id=\"syslogfacility22\">Local use 6</option>");
            builder.Append("<option  value=\"23\" id=\"syslogfacility23\">Local use 7</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"Syslog\">Encoding</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Choose the encoding of the syslog message according to the encoding capabilities of your syslog receiver.\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"syslogencoding_13\" value=\"0\" id=\"syslogencoding0\" >");
            builder.Append("<label for=\"syslogencoding0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("ANSI");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"syslogencoding_13\" value=\"1\" checked  id=\"syslogencoding1\" >");
            builder.Append("<label for=\"syslogencoding1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("UTF-8 (default)");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<label class=\"control-label has_help \" for=\"Syslog\">Message</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"The message to be sent (<a href='http://kb.paessler.com/en/topic/373' target='blank'>placeholders</a> allowed).<br/><br/><b>Note:</b> Enter a single * character (and nothing else) if you want to reset this field to the system default.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"message_13\" id=\"message_13\" autocomplete=\"off\" value=\"[%sitename] %device %name %status %down (%message)\" ></div>");
            builder.Append("</div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_14\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_14\" id=\"active_14\" value=\"14\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_14\" >Send SNMP Trap</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"SNMPTrap\">Host/IP</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the IP address or DNS name of the computer running the trap receiver. PRTG sends the trap on OID 1.3.6.1.4.1.32446\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"snmphost_14\" id=\"snmphost_14\" autocomplete=\"off\" value=\"localhost\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNMPTrap\">SNMP Port</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the SNMP port of the device for traps. Standard is 162.\">");
            builder.Append("<input class=\"text\"  data-rule-number=\"true\" data-rule-required=\"true\" type=\"text\" name=\"snmpport_14\" id=\"snmpport_14\" autocomplete=\"off\" value=\"162\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNMPTrap\">Community String</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the community string of the device. Standard is <b>public</b>.\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"snmpcommunity_14\" id=\"snmpcommunity_14\" autocomplete=\"off\" value=\"public\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNMPTrap\">Specific Trap Code</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter a code that helps you identify the purpose of the trap.\">");
            builder.Append("<input class=\"text\"  data-rule-number=\"true\" type=\"text\" name=\"snmptrapspec_14\" id=\"snmptrapspec_14\" autocomplete=\"off\" value=\"1\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNMPTrap\">Message ID</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter an ID that helps you identify the origin of the trap. It must be an integer value. PRTG sends it on the OID 1.3.6.1.4.1.32446.1.1.1\">");
            builder.Append("<input class=\"text\"  data-rule-number=\"true\" data-rule-required=\"true\" type=\"text\" name=\"messageid_14\" id=\"messageid_14\" autocomplete=\"off\" value=\"2\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNMPTrap\">Message</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"The message to be sent (<a href='http://kb.paessler.com/en/topic/373' target='blank'>placeholders</a> allowed).<br/><br/><b>Note:</b> Enter a single * character (and nothing else) if you want to reset this field to the system default. The message will be sent on OID 1.3.6.1.4.1.32446.1.1.4\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"message_14\" id=\"message_14\" autocomplete=\"off\" value=\"[%sitename] %device %name %status %down (%message)\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNMPTrap\">Agent IP</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the IP address of the sender. Leave this field empty to apply the IP of the PRTG web server.\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"senderip_14\" id=\"senderip_14\" autocomplete=\"off\" value=\"127.0.0.1\" ></div>");
            builder.Append("</div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_9\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_9\" id=\"active_9\" value=\"9\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_9\" >Execute HTTP Action</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"HTTP\">URL</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the URL to which PRTG sends the HTTP request.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"url_9\" id=\"url_9\" autocomplete=\"off\" value=\"http://localhost\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"HTTP\">SNI (Server Name Indication)</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select if PRTG will send the TLS/SSL SNI (Server Name Indication) extension when calling the URL.\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"urlsniselect_9\" value=\"0\" id=\"urlsniselect0\" >");
            builder.Append("<label for=\"urlsniselect0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Do not send SNI (default)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"urlsniselect_9\" value=\"1\" checked id=\"urlsniselect1\" >");
            builder.Append("<label for=\"urlsniselect1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Send SNI");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<span id=\"urlsniselectdepon\" class=\" Showurlsniselect1  Hideurlsniselect0  InitialDisplayNone  groupshowhideelement\">");
            builder.Append("<label class=\"control-label has_help \" for=\"HTTP\">Virtual Host (SNI)</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the SNI (Server Name Indication) name required by your endpoint provider. In most cases, this is the FQDN of the virtual host.\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"urlsniname_9\" id=\"urlsniname_9\" autocomplete=\"off\" value=\"test\" ></div>");
            builder.Append("</span>");
            builder.Append("<label class=\"control-label has_help \" for=\"HTTP\">Postdata</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter postdata that PRTG transmits to the URL (placeholders allowed).\">");
            builder.Append("<textarea class=\"textarea\"  id=\"postdata_9\" name=\"postdata_9\" rows=\"2\" >test</textarea></div>");
            builder.Append("</div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_10\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_10\" id=\"active_10\" value=\"10\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_10\" >Execute Program</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"EXE\">Program File</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select the program that PRTG executes. You can choose from *.exe, *.bat, *.cmd, *.com or *.ps1 files located in the Notifications/exe subfolder of your PRTG installation. If this list is empty, please copy all files you want to appear to the executables directory.\">");
            builder.Append("<select class=\"combo\"  data-rule-required=\"true\" name=\"address_10\" id=\"address_10\" ><option value=\"\">&lt;please select a file&gt;</option><option value=\"Demo EXE Notification - OutFile.bat\" selected=\"selected\">Demo exe notification - outfile.bat</option><option value=\"Demo EXE Notification - OutFile.ps1\">Demo exe notification - outfile.ps1</option></select></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EXE\">Parameter</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Parameters supplied to the executable (<a href='http://kb.paessler.com/en/topic/373' target='blank'>placeholders</a> allowed)\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"message_10\" id=\"message_10\" autocomplete=\"off\" value=\"[%sitename] %device %name %status %down (%message)\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EXE\">Domain or Computer Name</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Define a domain if you want to run the notification under another security context than of the PRTG probe service.\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"windowslogindomain_10\" id=\"windowslogindomain_10\" autocomplete=\"off\" value=\"contoso.local\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EXE\">Username</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter a username if you don't want to run the notification under the security context of the PRTG probe service.\">");
            builder.Append("<input class=\"text\"  type=\"text\" name=\"windowsloginusername_10\" id=\"windowsloginusername_10\" autocomplete=\"off\" value=\"administrator\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EXE\">Password</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter a password if you don't want to run the notification under the security context of the PRTG probe service.\">");
            builder.Append("<input class=\"text\"  type=\"password\" name=\"windowsloginpassword_10\" id=\"windowsloginpassword_10\" value=\"***\" autocomplete=\"off\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"EXE\">Timeout</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\" PRTG will kill the process if it has not finished after this time (in seconds).\">");
            builder.Append("<input class=\"text\"  data-rule-number=\"true\" data-rule-required=\"true\" type=\"text\" name=\"timeout_10\" id=\"timeout_10\" autocomplete=\"off\" value=\"60\" ></div>");
            builder.Append("</div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_15\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_15\" id=\"active_15\" value=\"15\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_15\" >Send Amazon Simple Notification Service Message</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"SNS\">AWS Access Key ID</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter your access key ID (obtained from aws.amazon.com).\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"accesskeyid_15\" id=\"accesskeyid_15\" autocomplete=\"off\" value=\"key\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNS\">AWS Secret Access Key</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter your secret access key (obtained from aws.amazon.com).\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"password\" name=\"secretaccesskeyid_15\" id=\"secretaccesskeyid_15\" value=\"pass\" autocomplete=\"off\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNS\">Location</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Choose the location of your Amazon service.\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"US-East\" id=\"amazonregionUS-East\" >");
            builder.Append("<label for=\"amazonregionUS-East\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("US East (Northern Virginia)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.us-east-2.amazonaws.com\" id=\"amazonregionsnsus-east-2amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnsus-east-2amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("US West (Ohio)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"US-West\" id=\"amazonregionUS-West\" >");
            builder.Append("<label for=\"amazonregionUS-West\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("US West (Northern California)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.us-west-2.amazonaws.com\" id=\"amazonregionsnsus-west-2amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnsus-west-2amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("US West (Oregon)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.ca-central-1.amazonaws.com\" id=\"amazonregionsnsca-central-1amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnsca-central-1amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Canada (Central)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"EU-West\" id=\"amazonregionEU-West\" >");
            builder.Append("<label for=\"amazonregionEU-West\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("EU West (Ireland)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.eu-central-1.amazonaws.com\" id=\"amazonregionsnseu-central-1amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnseu-central-1amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("EU Central (Frankfurt)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.eu-west-2.amazonaws.com\" id=\"amazonregionsnseu-west-2amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnseu-west-2amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("EU (London)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.ap-southeast-1.amazonaws.com\" id=\"amazonregionsnsap-southeast-1amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnsap-southeast-1amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Asia Pacific (Singapore)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.ap-southeast-2.amazonaws.com\" id=\"amazonregionsnsap-southeast-2amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnsap-southeast-2amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Asia Pacific (Sydney)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.ap-northeast-2.amazonaws.com\" id=\"amazonregionsnsap-northeast-2amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnsap-northeast-2amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Asia Pacific (Seoul)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.ap-northeast-1.amazonaws.com\" id=\"amazonregionsnsap-northeast-1amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnsap-northeast-1amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Asia Pacific (Tokyo)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.ap-south-1.amazonaws.com\" id=\"amazonregionsnsap-south-1amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnsap-south-1amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Asia Pacific (Mumbai)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"amazonregion_15\" value=\"sns.sa-east-1.amazonaws.com\" id=\"amazonregionsnssa-east-1amazonawscom\" >");
            builder.Append("<label for=\"amazonregionsnssa-east-1amazonawscom\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("South America (São Paulo)");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNS\">ARN</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the Amazon Resource Name.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"arn_15\" id=\"arn_15\" autocomplete=\"off\" value=\"customResource\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNS\">Subject</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the 'subject' part of the message.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"subject_15\" id=\"subject_15\" autocomplete=\"off\" value=\"message subject\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"SNS\">Message</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"The message to be sent (<a href='http://kb.paessler.com/en/topic/373' target='blank'>placeholders</a> allowed).<br/><br/><b>Note:</b> Enter a single * character (and nothing else) if you want to reset this field to the system default.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"message_15\" id=\"message_15\" autocomplete=\"off\" value=\"[%sitename] %device %name %status %down (%message)\" ></div>");
            builder.Append("</div></fieldset>");
            builder.Append("<fieldset class=\"collapsed\">");
            builder.Append("<legend class=\"prtg-header\"><input name=\"active_16\" type=\"hidden\" value=\"1\"><input class=\"toggleFieldset GroupShowHide checkbox\" type=\"checkbox\" name=\"active_16\" id=\"active_16\" value=\"16\" checked=\"checked\" style=\"display: none; \">");
            builder.Append("<label for=\"active_16\" >Assign Ticket</label>");
            builder.Append("</legend>");
            builder.Append("<div class=\"control-group\">");
            builder.Append("<label class=\"control-label has_help \" for=\"TicketNoti\">Assign to User or User Group</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Choose if PRTG assigns the ticket to a specific user or to a user group.\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"isusergroup_16\" value=\"1\" checked  id=\"isusergroup1\" >");
            builder.Append("<label for=\"isusergroup1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("To User Group");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio  GroupShowHide\" name=\"isusergroup_16\" value=\"0\" id=\"isusergroup0\" >");
            builder.Append("<label for=\"isusergroup0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("To User");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("<span id=\"assignusergroupon\" class=\" Showisusergroup1  Hideisusergroup0  groupshowhideelement\">");
            builder.Append("<label class=\"control-label has_help \" for=\"TicketNoti\">Assign Ticket to this User Group</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select a user group to which PRTG assigns the notification ticket.\">");
            builder.Append("<select name=\"addressgroupid_16\" id=\"addressgroupid_16\" >");
            builder.Append("<option value=\"200|PRTG Administrators\" selected=\"selected\" >PRTG Administrators</option>");
            builder.Append("<option value=\"201|PRTG Users Group\">PRTG Users Group</option></select></div>");
            builder.Append("</span>");
            builder.Append("<span id=\"assignuseron\" class=\" Showisusergroup0  Hideisusergroup1  InitialDisplayNone  groupshowhideelement\">");
            builder.Append("<label class=\"control-label has_help \" for=\"TicketNoti\">Assign Ticket to this User</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Select a user to which PRTG assigns the notification ticket.\">");
            builder.Append("<select name=\"ticketuserid_16\" id=\"ticketuserid_16\" >");
            builder.Append("<option value=\"100|PRTG System Administrator\" selected=\"selected\" >PRTG System Administrator</option></select></div>");
            builder.Append("</span>");
            builder.Append("<label class=\"control-label has_help \" for=\"TicketNoti\">Subject</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the 'subject' part of the ticket.\">");
            builder.Append("<input class=\"text\"  data-rule-required=\"true\" type=\"text\" name=\"subject_16\" id=\"subject_16\" autocomplete=\"off\" value=\"%device %name %status %down (%message)\" ></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"TicketNoti\">Content</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"Enter the content of the ticket (placeholders allowed).\">");
            builder.Append("<textarea class=\"textarea\"  data-rule-required=\"true\" id=\"message_16\" name=\"message_16\" rows=\"2\" >");
            builder.Append("Sensor: %name");
            builder.Append("Status: %status %down");
            builder.Append("Date/Time: %datetime (%timezone)");
            builder.Append("Last Result: %lastvalue");
            builder.Append("Last Message: %message");
            builder.Append("Probe: %probe");
            builder.Append("Group: %group");
            builder.Append("Device: %device (%host)");
            builder.Append("Last Scan: %lastcheck");
            builder.Append("Last Up: %lastup");
            builder.Append("Last Down: %lastdown");
            builder.Append("Uptime: %uptime");
            builder.Append("Downtime: %downtime");
            builder.Append("Cumulated since: %cumsince");
            builder.Append("Location: %location");
            builder.Append("</textarea> <a class=\"resettodefaultlink\" href=\"#\" onclick=\"$('#message_16').val('*').hide();$(this).replaceWith('Default will be set when you submit this page.'); $('body .tooltip').remove();return false\" title=\"Reset to default\"><span class=\"icon ui-icon ui-icon-trash\"></span></a></div>");
            builder.Append("<label class=\"control-label has_help \" for=\"TicketNoti\">When Condition Clears</label>");
            builder.Append("<div class=\"controls \" data-placement=\"right\" data-helptext=\"PRTG can close the tickets automatically for you when the condition that triggered the ticket clears.\">");
            builder.Append("<div class=\"radio-control\">");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"autoclose_16\" value=\"1\" checked  id=\"autoclose1\" >");
            builder.Append("<label for=\"autoclose1\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Close ticket automatically (recommended)");
            builder.Append("</label>");
            builder.Append("<input type=\"radio\" class=\"hidden radio \" name=\"autoclose_16\" value=\"0\" id=\"autoclose0\" >");
            builder.Append("<label for=\"autoclose0\" class=\"radio-control-label\">");
            builder.Append("<i class=\"icon-gray icon-radio-on\"></i>");
            builder.Append("Leave ticket open");
            builder.Append("</label>");
            builder.Append("</div>");
            builder.Append("</div>");
            builder.Append("</div></fieldset>");
            builder.Append("    <input type=\"hidden\" name=\"id\" value=\"301\">");
            builder.Append("    <input type=hidden name=\"targeturl\" value=\"/myaccount.htm?tabid=2\">");
            builder.Append("    <div class=\"quick-action-wrapper\" style=\"\" >");
            builder.Append("        <button class=\"submit actionbutton quick-action-button\" type=\"submit\">Save</button>");
            builder.Append("        <button  type=\"submit\" class='ui-icon quick-action-badge continue-badge '></button>");
            builder.Append("    </div>");
            builder.Append("</form>");

            return builder.ToString();
        }

        public override XElement GetItem(NotificationActionItem item)
        {
            var xml = new XElement("item",
                new XElement("objid", item.ObjId),
                new XElement("name", item.Name),
                new XElement("type", item.Type),
                new XElement("type_raw", item.TypeRaw),
                new XElement("active", item.Active),
                new XElement("active_raw", item.Active)
            );

            return xml;
        }

        public override string GetResponseText(ref string address)
        {
            if (address.Contains(HtmlFunction.EditNotification.GetDescription()))
            {
                return GetSettingsResponseText(address);
            }

            return base.GetResponseText(ref address);
        }
    }
}
